### ISSUE TITLE
想问一下dna-compiler和dna-annotations这两个项目在哪

### ISSUE THREAD

**Issue by zhouyishenglan** [eleme/dna#3]
编译报错:
Caused by: org.gradle.api.UnknownProjectException: Project with path ':dna-compiler' could not be found in project ':dna'.

**Comment by Assuner-Lee** [comment]
> 编译报错:
> Caused by: org.gradle.api.UnknownProjectException: Project with path ':dna-compiler' could not be found in project ':dna'.

更新了readme，你看下

**Comment by zhouyishenglan** [comment]
麻烦你将lib的build.gradle也改一下，虽然可以自己修改，谢谢啦
annotationProcessor project(':dna-compiler')
implementation project(':dna-annotations')

**Comment by Assuner-Lee** [comment]
> 麻烦你将lib的build.gradle也改一下，虽然可以自己修改，谢谢啦
> annotationProcessor project(':dna-compiler')
> implementation project(':dna-annotations')

你再看下，改好了
